# frozen_string_literal: true

module AlphaExecutionService
  class << self
    # Entry point for executing an alpha signal.
    # @param signal [Hash] The signal generated by SignalEngine
    # @return [Hash] Result of execution { status: :success/:failure, reason: ..., order_id: ... }
    def execute(signal)
      return failure("Invalid signal") unless signal_valid?(signal)

      # 1. Global Kill Switch Check
      cb = Risk::CircuitBreaker.instance
      return failure("Circuit breaker tripped") if cb.tripped?

      # 2. Risk Limits Check
      risk_check = Risk::LimitsGuard.check_all!
      return failure(risk_check[:blocked]) if risk_check[:blocked]

      # 3. Directional Locking (Conflict check)
      return failure("Conflicting position exists for #{signal[:index_key]}") if conflicting_position?(signal)
      
      # 3b. AI Alpha Gate Check
      return failure("Trade blocked by AI Risk Manager") unless Ai::AlphaGate.approve?(signal)

      # 4. Find the tradable Derivative
      # Safety: Re-verify ATM strike if index has moved since signal timestamp
      current_ltp = fetch_current_index_ltp(signal[:index_key])
      if current_ltp && signal[:underlying_ltp] && (current_ltp - signal[:underlying_ltp].to_f).abs > (current_ltp * 0.005)
        # Index moved > 0.5%, re-calculate strike
        new_strike = atm_strike(current_ltp, signal[:index_key])
        Rails.logger.info "[AlphaExecutionService] Index moved from #{signal[:underlying_ltp]} to #{current_ltp}. Adjusting strike from #{signal[:strike]} to #{new_strike}"
        signal[:strike] = new_strike
        signal[:underlying_ltp] = current_ltp
      end

      derivative = find_derivative(signal)
      return failure("Derivative not found for #{signal[:index_key]} strike #{signal[:strike]}") unless derivative

      # 5. No-Averaging Rule
      return failure("Position already active for this security") if existing_tracker?(derivative)

      # 6. Execute Order
      # Build metadata for the existing execution pipeline
      meta = {
        alpha_source: signal[:alpha_source].to_s,
        signal_confidence: signal[:confidence].to_f,
        expected_value: signal[:expected_value].to_f,
        entry_strategy: "alpha_#{signal[:alpha_source]}",
        signal_timestamp: signal[:timestamp],
        direction: signal[:direction].to_s,
        index_key: signal[:index_key].to_s,
        client_order_id: "ALPHA_#{SecureRandom.hex(4).upcase}"
      }

      # Signal context for Capital::Allocator
      index_cfg = {
        key: signal[:index_key].to_s,
        confidence: signal[:confidence].to_f,
        stop_loss: signal[:stop_loss].to_f,
        target: signal[:target].to_f,
        lot_size: signal[:lot_size]
      }

      # Existing logic: resolve_ltp -> sizing -> order_placer -> tracker
      order = derivative.buy_option!(
        product_type: 'INTRADAY',
        index_cfg: index_cfg,
        meta: meta
      )

      if order&.respond_to?(:order_id) && order.order_id.present?
        # Update Audit Trail
        record_signal_audit!(signal, order.order_id, 'executed')
        # Record trade in Risk Limits
        Risk::LimitsGuard.record_trade!
        
        success(order, signal)
      else
        record_signal_audit!(signal, nil, 'failed')
        failure("Order placement failed via gateway")
      end
    rescue StandardError => e
      DhanhqErrorHandler.handle_dhanhq_error(e, context: "AlphaExecutionService(#{signal[:index_key]})")
      failure("#{e.class}: #{e.message}")
    end

    private

    def signal_valid?(signal)
      signal.is_a?(Hash) && signal[:index_key].present? && signal[:direction].present?
    end

    def find_derivative(signal)
      Derivative.find_by_params(
        underlying_symbol: signal[:index_key].to_s.upcase,
        strike_price: signal[:strike],
        expiry_date: signal[:expiry],
        option_type: signal[:direction].to_s.upcase
      )
    end

    def fetch_current_index_ltp(index_key)
      instrument = Instrument.find_by(symbol_name: index_key.to_s.upcase, segment: 'index')
      return nil unless instrument
      
      cfg = AlphaStrategy::INDEX_CONFIG[index_key.to_sym]
      return nil unless cfg
      
      instrument.resolve_ltp(segment: cfg[:exchange_segment], security_id: cfg[:security_id])
    end

    def atm_strike(ltp, index_key)
      cfg = AlphaStrategy::INDEX_CONFIG[index_key.to_sym]
      return 0 unless cfg
      step = cfg[:tick_step]
      (ltp.to_f / step).round * step
    end

    def conflicting_position?(signal)
      # Check if an active position exists in the OPPOSITE direction for the same index
      opposite_direction = signal[:direction].to_s.downcase == 'ce' ? 'pe' : 'ce'
      PositionTracker.active.where("meta->>'index_key' = ? AND meta->>'direction' = ?", signal[:index_key].to_s, opposite_direction).exists?
    end

    def existing_tracker?(derivative)
      PositionTracker.active.exists?(
        segment: derivative.exchange_segment,
        security_id: derivative.security_id.to_s
      )
    end

    def record_signal_audit!(signal, order_id, status)
      AlphaSignal.create!(
        index_key: signal[:index_key].to_s,
        direction: signal[:direction].to_s,
        alpha_source: signal[:alpha_source].to_s,
        strike_price: signal[:strike],
        expiry_date: signal[:expiry],
        confidence: signal[:confidence],
        expected_value: signal[:expected_value],
        status: status,
        order_id: order_id,
        iv_context: signal[:iv_context]&.to_json
      )
    rescue StandardError => e
      Rails.logger.error "[AlphaExecutionService] Signal audit failed: #{e.message}"
    end

    def success(order, signal)
      { status: :success, order_id: order.order_id, source: signal[:alpha_source] }
    end

    def failure(reason)
      { status: :failure, reason: reason }
    end
  end
end
