# frozen_string_literal: true

# Usage:
#   rake arch:scan                    # prints TypeScript to stdout
#   rake arch:scan[architecture-dashboard/src/lib/architecture-data.ts]  # writes to file
#   npm run scan --prefix architecture-dashboard  # uses the package.json script alias

namespace :arch do
  desc 'Scan codebase and generate architecture-data.ts for the architecture dashboard'
  task :scan, [:output_path] => :environment do |_t, args|
    data = ArchScanner.scan
    ts = ArchScanner.to_typescript(data)

    if args[:output_path]
      File.write(args[:output_path], ts)
      puts "[arch:scan] Wrote #{args[:output_path]} (#{ts.lines.count} lines)"
    else
      puts ts
    end
  end
end

# ─── Scanner ────────────────────────────────────────────────────────
# Mirrors scripts/scan_architecture.rb (standalone, no Rails). Keep both in sync.
class ArchScanner
  class << self
    REPO_ROOT = File.expand_path('../..', __dir__)

    def scan
      svcs = scan_services
      guards = scan_entry_guards
      rules = scan_risk_rules
      opts = scan_options_strategies
      tables = scan_db_tables
      endpoints = scan_api_endpoints
      jobs = scan_recurring_jobs
      ai = scan_ai_subsystems

      {
        generated_at: Time.now.strftime('%Y-%m-%d %H:%M'),
        deltas: build_deltas(svcs, guards, rules, tables, endpoints, jobs, ai),
        services: svcs,
        entry_guards: guards,
        risk_rules: rules,
        options_strategies: opts,
        db_tables: tables,
        api_endpoints: endpoints,
        recurring_jobs: jobs,
        ai_subsystems: ai,
        env_vars: scan_env_vars,
      }
    end

    def to_typescript(data)
      <<~TS
        // AUTO-GENERATED by rake arch:scan at #{data[:generated_at]}
        // DO NOT EDIT MANUALLY — regenerate with: rake arch:scan[architecture-dashboard/src/lib/architecture-data.ts]

        export interface Delta { metric: string; review: string; actual: string; direction: 'up' | 'down' | 'same'; }

        export const deltas: Delta[] = #{ts_array(data[:deltas], :delta)};

        export interface Service { key: string; name: string; cls: string; cadence: string; category: string; status: string; }
        export const services: Service[] = #{ts_array(data[:services], :service)};

        export interface Guard { name: string; category: string; description: string; isNew: boolean; }
        export const entryGuards: Guard[] = #{ts_array(data[:entry_guards], :guard)};

        export const riskRules: string[] = #{ts_array(data[:risk_rules], :str)};

        export const optionsBuyingStrategies: string[] = #{ts_array(data[:options_strategies], :str)};

        export interface DbTable { table: string; category: string; isNew: boolean; }
        export const dbTables: DbTable[] = #{ts_array(data[:db_tables], :db_table)};

        export interface ApiEndpoint { method: string; path: string; isNew: boolean; }
        export const apiEndpoints: ApiEndpoint[] = #{ts_array(data[:api_endpoints], :api_endpoint)};

        export interface RecurringJob { name: string; schedule: string; phase: string; }
        export const recurringJobs: RecurringJob[] = #{ts_array(data[:recurring_jobs], :recurring_job)};

        export interface AiSubsystem { name: string; path: string; components: string[]; description: string; status: string; }
        export const aiSubsystems: AiSubsystem[] = #{ts_array(data[:ai_subsystems], :ai_subsystem)};

        // ─── Static Data (manually curated from repo audit, update as needed) ─────────
        export interface TechLayer { layer: string; technology: string; }
        export const techStack: TechLayer[] = #{ts_array(default_tech_stack, :tech_layer)};

        export interface ProcessModel { process: string; command: string; role: string; }
        export const processModel: ProcessModel[] = #{ts_array(default_process_model, :process_model)};

        export const indexParams = #{ts_array(default_index_params, :index_param)};
        export const smcDetectors: string[] = #{ts_array(default_smc_detectors, :str)};
        export const lockedPaths: string[] = #{ts_array(default_locked_paths, :str)};
        export const alphaPaths: string[] = #{ts_array(default_alpha_paths, :str)};
        export const tokenFallback: string[] = #{ts_array(default_token_fallback, :str)};
        export const bootSequence: string[] = #{ts_array(default_boot_sequence, :str)};
        export const docDebt: string[] = #{ts_array(default_doc_debt, :str)};
        export const criticalInvariants: string[] = #{ts_array(default_invariants, :str)};

        export interface EnvVar { variable: string; required: string; purpose: string; }
        export const envVars: EnvVar[] = #{ts_array(data[:env_vars], :env)};

        export interface NewSubsystem { name: string; path: string; fileCount: number; description: string; }
        export const newSubsystems: NewSubsystem[] = #{ts_array(default_new_subsystems, :new_subsystem)};

        export interface Concern { severity: string; title: string; description: string; }
        export const concerns: Concern[] = #{ts_array(default_concerns, :concern)};
      TS
    end

    private

    # ─── Scanners ──────────────────────────────────────────────────

    def scan_services
      svcs = []
      bootstrap_file = File.join(REPO_ROOT, 'lib', 'trading_system', 'bootstrap.rb')
      if File.exist?(bootstrap_file)
        File.read(bootstrap_file).scan(/register\(\s*:(\w+)\s*,\s*([\w:]+)(?:,\s*[^)]*cadence:\s*['"]([^'"]*)['"])?/).each do |m|
          key, cls, cadence = m
          svcs << { key:, name: humanize(key), cls:, cadence: cadence || 'on_tick', category: guess_service_category(key, cls), status: 'active' }
        end
      end
      strategy_dir = File.join(REPO_ROOT, 'strategies')
      if Dir.exist?(strategy_dir)
        Dir.glob(File.join(strategy_dir, '*/manifest.yml')).each do |mf|
          key = File.basename(File.dirname(mf))
          svcs << { key:, name: humanize(key), cls: "strategies/#{key}", cadence: 'plugin', category: 'strategy', status: 'active' }
        end
      end
      svcs.uniq { |s| s[:key] }
    end

    def scan_entry_guards
      guards = []
      guards_dir = File.join(REPO_ROOT, 'app', 'services', 'entries', 'guards')
      if Dir.exist?(guards_dir)
        Dir.glob(File.join(guards_dir, '*.rb')).sort.each do |f|
          name = File.basename(f, '.rb').tr('_', ' ')
          desc = extract_first_comment(File.read(f)) || name
          guards << { name:, category: guess_guard_category(name).capitalize, description: desc, isNew: false }
        end
      end
      vg = File.join(REPO_ROOT, 'app', 'services', 'signal', 'validation_gates.rb')
      if File.exist?(vg)
        File.read(vg).scan(/def\s+(check_\w+)/).flatten.each do |m|
          name = m.sub('check_', '').tr('_', ' ')
          guards << { name:, category: 'Signal', description: "Signal validation: #{name}", isNew: false }
        end
      end
      guards
    end

    def scan_risk_rules
      rules_dir = File.join(REPO_ROOT, 'app', 'services', 'risk', 'rules')
      return [] unless Dir.exist?(rules_dir)
      Dir.glob(File.join(rules_dir, '*_rule.rb')).sort.map { |f| File.basename(f, '.rb') }
    end

    def scan_options_strategies
      sd = File.join(REPO_ROOT, 'app', 'services', 'options_buying', 'strategies')
      return [] unless Dir.exist?(sd)
      Dir.glob(File.join(sd, '*.rb')).sort.map { |f| File.basename(f, '.rb') }
    end

    def scan_db_tables
      schema_file = File.join(REPO_ROOT, 'db', 'schema.rb')
      return [] unless File.exist?(schema_file)
      File.read(schema_file).scan(/create_table\s+"(\w+)"/).flatten.map do |t|
        { table: t, category: guess_table_category(t).capitalize, isNew: false }
      end
    end

    def scan_api_endpoints
      routes_file = File.join(REPO_ROOT, 'config', 'routes.rb')
      return [] unless File.exist?(routes_file)
      endpoints = []
      content = File.read(routes_file)
      content.scan(/(get|post|put|patch|delete|match)\s+['"]([^'"]+)['"]/).each do |m|
        method = m[0].upcase
        path = m[1]
        next if path == '/cable' || path.include?('rails/')
        endpoints << { method:, path:, isNew: false }
      end
      content.scan(/resources\s+:(\w+)/).flatten.each do |r|
        endpoints << { method: 'REST', path: "/#{r}", isNew: false }
        endpoints << { method: 'REST', path: "/#{r}/:id", isNew: false }
      end
      endpoints.uniq { |e| "#{e[:method]} #{e[:path]}" }
    end

    def scan_recurring_jobs
      recurring_file = File.join(REPO_ROOT, 'config', 'recurring.yml')
      return [] unless File.exist?(recurring_file)
      require 'yaml'
      yaml = YAML.safe_load(File.read(recurring_file))
      jobs = yaml['production'] || yaml
      (jobs || {}).map do |key, cfg|
        cls = cfg['class'].to_s
        name = cls.empty? ? humanize(key) : cls.split('::').last
        { name:, schedule: humanize_schedule(cfg['schedule'].to_s), phase: guess_job_phase(cfg['schedule'].to_s) }
      end
    end

    def scan_ai_subsystems
      dirs = [
        { p: 'app/services/ai/trading_bot', n: 'Trading Bot', d: 'Semi-autonomous scan-analyze-trade loop (Ollama-backed polling)', s: 'active' },
        { p: 'app/services/ai/trading_agent', n: 'Trading Agent', d: 'LLM tool-calling agent with REPL and audit trace', s: 'active' },
        { p: 'app/services/ai/calibration', n: 'AI Calibration', d: 'Weekly automated indicator calibration via LLM', s: 'active' },
        { p: 'app/services/ai/autonomous', n: 'Autonomous', d: 'LLM experiment runner with Observe-Think-Act loop', s: 'experimental' },
        { p: 'app/services/auto_exp', n: 'AutoExp', d: 'LLM-driven automated config experiments: plan - backtest - evaluate - apply', s: 'new' },
        { p: 'app/services/agents', n: 'Trading Orchestrator', d: 'LLM-chained MarketAnalyst - Strategy - Risk - OptionSelector pipeline', s: 'overlapping' },
      ]
      dirs.filter_map do |dir|
        full_path = File.join(REPO_ROOT, dir[:p])
        next unless Dir.exist?(full_path)
        components = Dir.glob(File.join(full_path, '*.rb')).map { |f| File.basename(f, '.rb') }.sort
        next if components.empty?
        { name: dir[:n], path: dir[:p], components:, description: dir[:d], status: dir[:s] }
      end
    end

    def scan_env_vars
      vars = {}
      env_file = File.join(REPO_ROOT, '.env')
      if File.exist?(env_file)
        File.read(env_file).scan(/^([A-Z_][A-Z0-9_]*)=/).flatten.each { |v| vars[v] = 'Yes' }
      end
      ['.env.example', '.env.sample'].each do |example_file|
        path = File.join(REPO_ROOT, example_file)
        next unless File.exist?(path)
        File.read(path).scan(/^([A-Z_][A-Z0-9_]*)=/).flatten.each { |v| vars[v] ||= 'Recommended' }
      end
      vars.map { |variable, required| { variable:, required:, purpose: '' } }
    end

    def build_deltas(svcs, guards, rules, tables, endpoints, jobs, ai)
      [
        ['Registered Services', '19', svcs.size],
        ['Entry Guards', '33', guards.size],
        ['AI Subsystems', '4', ai.size],
        ['API Endpoints', '68', endpoints.size],
        ['Recurring Jobs', '31', jobs.size],
        ['DB Tables', '58', tables.size],
        ['Signal Paths', '2', '3 (all active)'],
        ['Risk Rules', '~8', rules.size],
      ].map do |metric, review, actual|
        direction = actual.is_a?(Integer) ? (actual > review.to_i ? 'up' : actual < review.to_i ? 'down' : 'same') : 'up'
        { metric:, review:, actual: actual.to_s, direction: }
      end
    end

    # ─── Guessing Helpers ────────────────────────────────────────

    def guess_service_category(key, _cls)
      k = key.to_s.downcase
      return 'market' if k.include?('feed') || k.include?('tick') || k.include?('market') || k.include?('option_chain')
      return 'signal' if k.include?('signal') || k.include?('scheduler') || k.include?('entry')
      return 'risk' if k.include?('risk') || k.include?('circuit') || k.include?('limit') || k.include?('guard')
      return 'position' if k.include?('position') || k.include?('trailing') || k.include?('pnl') || k.include?('heartbeat')
      return 'order' if k.include?('order') || k.include?('executor') || k.include?('bracket')
      return 'exit' if k.include?('exit') || k.include?('stop') || k.include?('profit')
      return 'cache' if k.include?('cache') || k.include?('warm') || k.include?('sync')
      return 'smc' if k.include?('smc') || k.include?('ict') || k.include?('structure')
      return 'strategy' if k.include?('strategy') || k.include?('deploy')
      return 'paper' if k.include?('paper') || k.include?('wallet')
      return 'candle' if k.include?('candle') || k.include?('ohlc')
      'stats'
    end

    def guess_guard_category(name)
      n = name.downcase
      return 'timing' if n.include?('time') || n.include?('session') || n.include?('market_open')
      return 'trend' if n.include?('trend') || n.include?('direction') || n.include?('momentum')
      return 'volatility' if n.include?('volatility') || n.include?('atr') || n.include?('vix')
      return 'capital' if n.include?('capital') || n.include?('lot') || n.include?('size') || n.include?('quantity')
      return 'risk' if n.include?('risk') || n.include?('drawdown') || n.include?('loss') || n.include?('circuit')
      return 'signal' if n.include?('signal') || n.include?('confluence') || n.include?('quality')
      return 'market' if n.include?('market') || n.include?('regime') || n.include?('permission')
      return 'expiry' if n.include?('expiry') || n.include?('dte')
      'general'
    end

    def guess_table_category(table)
      t = table.downcase
      return 'trading' if t.include?('position') || t.include?('signal') || t.include?('order') || t.include?('trade')
      return 'auth' if t.include?('token') || t.include?('session')
      return 'research' if t.include?('research') || t.include?('experiment') || t.include?('backtest')
      return 'system' if t.include?('setting') || t.include?('log') || t.include?('audit')
      return 'market' if t.include?('instrument') || t.include?('derivative') || t.include?('candle') || t.include?('holiday')
      return 'strategy' if t.include?('strategy') || t.include?('calibration') || t.include?('alpha')
      return 'ledger' if t.include?('ledger') || t.include?('journal') || t.include?('wallet')
      'other'
    end

    def guess_job_phase(schedule)
      s = schedule.to_s.downcase
      return 'weekly' if s.include?('sunday')
      return 'intraday' if s.include?('minute') || s.include?('min ')
      return 'post-close' if s.include?('pm')
      return 'pre-market' if s.include?('am')
      'intraday'
    end

    def humanize_schedule(s)
      s = s.to_s
      s = s.sub(/\Aat /, '')
      s = s.sub(/every Sunday at /, 'Sunday ')
      s = s.sub(/Asia\/Kolkata/, 'IST')
      s = s.sub(/every weekday\z/, 'weekdays')
      s = s.sub(/ every weekday\z/, ' weekdays')
      s = s.sub(/\bevery day\z/, 'weekdays')
      s = s.sub(/minutes/, 'min')
      s = s.sub(/every hour at minute \d+/, 'every hour')
      s = s.sub(/between ([0-9:]+)(am|pm) and ([0-9:]+)(am|pm)/, '(\1\2-\3\4)')
      s = s.sub(/ on weekdays/, '')
      s.strip
    end

    def extract_first_comment(content)
      comment = content.lines.reject { |l| l.include?('frozen_string_literal') }
                        .find { |l| l.match?(/^\s*#/) }&.sub(/^\s*#\s*/, '')&.strip
      comment && comment.length > 80 ? "#{comment[0, 80]}..." : comment
    end

    def humanize(s)
      s.to_s.tr('_', ' ').gsub(/\b\w/, &:upcase)
    end

    # ─── TypeScript Serialization ────────────────────────────────

    def ts_array(items, type)
      return '[]' unless items && items.any?
      lines = items.map { |item| '  ' + ts_object(item, type) }
      "[\n#{      lines.join(",\n")}\n]"
    end

    def ts_object(item, type)
      case type
      when :delta
        "{ metric: '#{esc(item[:metric])}', review: '#{esc(item[:review])}', actual: '#{esc(item[:actual])}', direction: '#{item[:direction]}' }"
      when :service
        "{ key: '#{esc(item[:key])}', name: '#{esc(item[:name])}', cls: '#{esc(item[:cls])}', cadence: '#{esc(item[:cadence])}', category: '#{item[:category]}', status: '#{item[:status]}' }"
      when :guard
        "{ name: '#{esc(item[:name])}', category: '#{esc(item[:category])}', description: '#{esc(item[:description])}', isNew: #{item[:isNew]} }"
      when :db_table
        "{ table: '#{esc(item[:table])}', category: '#{esc(item[:category])}', isNew: #{item[:isNew]} }"
      when :api_endpoint
        "{ method: '#{esc(item[:method])}', path: '#{esc(item[:path])}', isNew: #{item[:isNew]} }"
      when :recurring_job
        "{ name: '#{esc(item[:name])}', schedule: '#{esc(item[:schedule])}', phase: '#{item[:phase]}' }"
      when :ai_subsystem
        comps = item[:components].map { |c| "'#{esc(c)}'" }.join(', ')
        "{ name: '#{esc(item[:name])}', path: '#{esc(item[:path])}', components: [#{comps}], description: '#{esc(item[:description])}', status: '#{item[:status]}' }"
      when :tech_layer
        "{ layer: '#{esc(item[:layer])}', technology: '#{esc(item[:technology])}' }"
      when :process_model
        "{ process: '#{esc(item[:process])}', command: '#{esc(item[:command])}', role: '#{esc(item[:role])}' }"
      when :index_param
        "{ index: '#{esc(item[:index])}', capital: '#{esc(item[:capital])}', premium: '#{esc(item[:premium])}', risk: '#{esc(item[:risk])}', maxTrades: #{item[:maxTrades]} }"
      when :env
        "{ variable: '#{esc(item[:variable])}', required: '#{esc(item[:required])}', purpose: '#{esc(item[:purpose])}' }"
      when :new_subsystem
        "{ name: '#{esc(item[:name])}', path: '#{esc(item[:path])}', fileCount: #{item[:fileCount]}, description: '#{esc(item[:description])}' }"
      when :concern
        "{ severity: '#{esc(item[:severity])}', title: '#{esc(item[:title])}', description: '#{esc(item[:description])}' }"
      when :str
        "'#{esc(item)}'"
      else
        "'#{esc(item.to_s)}'"
      end
    end

    def esc(str)
      str.to_s.gsub("'", "\\'").gsub("\n", ' ')
    end

    # ─── Default Static Data ─────────────────────────────────────

    def default_tech_stack
      [
        { layer: 'Language/Framework', technology: 'Ruby 3.3.4, Rails 8.1.3 (API-only)' },
        { layer: 'Job Backend', technology: 'Solid Queue' },
        { layer: 'WebSocket', technology: 'Solid Cable' },
        { layer: 'Cache', technology: 'Solid Cache' },
        { layer: 'Database', technology: 'PostgreSQL 15' },
        { layer: 'Queue Store', technology: 'Redis 7' },
        { layer: 'Broker API', technology: 'DhanHQ v2' },
        { layer: 'LLM Runtime', technology: 'Ollama (local)' },
        { layer: 'AI Framework', technology: 'ruby_llm-agents' },
        { layer: 'Frontend', technology: 'Vite + SolidJS/Vue (main), Next.js (arch)' },
        { layer: 'Deployment', technology: 'Docker Compose (6 processes)' },
      ]
    end

    def default_process_model
      [
        { process: 'web', command: 'bin/rails server (Puma)', role: 'Rails API — REST endpoints, WebSocket cable, static assets' },
        { process: 'jobs', command: 'bin/jobs (Solid Queue)', role: 'Background jobs — scheduled tasks, research pipeline' },
        { process: 'dashboard', command: 'Vite / nginx :3000', role: 'Main trading dashboard — positions, signals, option chain' },
        { process: 'arch-dashboard', command: 'Next.js standalone :3003', role: 'Architecture dashboard — live codebase visualization' },
      ]
    end

    def default_index_params
      [
        { index: 'NIFTY', capital: '30%', premium: '30-160', risk: '1%', maxTrades: 3 },
        { index: 'BANKNIFTY', capital: '30%', premium: '60-650', risk: '2%', maxTrades: 3 },
        { index: 'SENSEX', capital: '30%', premium: '40-320', risk: '2%', maxTrades: 3 },
      ]
    end

    def default_smc_detectors
      [
        'fvg', 'order_blocks', 'liquidity', 'structure',
        'swing_structure', 'internal_structure', 'premium_discount',
      ]
    end

    def default_locked_paths
      [
        'DhanHQ gateways/adapters',
        'WebSocket/market-data/caching (market_feed_hub, order_update_hub, redis_tick_cache)',
        'Position lifecycle (active_cache, serializer, positions/states/*)',
        'Order execution plumbing (orders/commands/*, executor, entry_manager, FSM, bracket placer)',
        'Exit engine (exit_engine, trailing_engine, mfe_exit_engine, gamma_trailing_engine)',
        'Risk-manager plumbing',
        'Process wiring (lib/trading_system/, jobs, controllers/routes)',
        'Instrument/chain plumbing (instrument.rb, chain_analyzer.rb, strike_selector.rb)',
      ]
    end

    def default_alpha_paths
      [
        'signal/*',
        'indicators/*',
        'market_state/*', 'market_context/*',
        'smc/*',
        'trading/trend_scorer.rb',
        'trading/permission_resolver.rb',
        'entries/entry_guard.rb, entry_filter_engine, entry_guard_pipeline',
        'All entries/guards/*',
        'orders/analyzer.rb, adjuster.rb, adaptive_trailing.rb, gamma_detector.rb',
        'All risk/*, all policies/*',
        'capital/allocator.rb',
        'options/flow_analyzer.rb, strike_qualification/*',
        'options/historical_calibration_engine.rb',
        'auto_exp/* (new experiment framework)',
        'backtest/* (new backtest subsystem)',
        'event_store/* (new decision audit trail)',
      ]
    end

    def default_token_fallback
      [
        'Authority server HTTP GET ($TRADER_API_BASE_URL/auth/dhan/token, 60s cache)',
        'TOTP auto-refresh (DHAN_PIN + DHAN_TOTP_SECRET via rotp gem)',
        'Static ENV["DHAN_ACCESS_TOKEN"] fallback',
      ]
    end

    def default_boot_sequence
      [
        'Rails initializers wire DhanHQ config, gateway (paper/live), token bootstrap',
        'Live::PositionSyncService.instance.force_sync! - reconcile DB vs broker',
        'Market::VixGate.evaluate! at boot (VIX entry gating)',
        'supervisor.start_all - launches all daemon services',
      ]
    end

    def default_doc_debt
      [
        'README.md describes 11-service supervisor; actual registry has 16 entries',
        'Signal::Scheduler IS still registered - coexists with Strategies::Manager',
        'Entry guard count documented as 20; actual directory has 40+ guard files',
        'docs/ has ~200+ files, many under docs/archive/ (superseded)',
        '~200 backtest artifact files committed to lib/ (should be in .gitignore)',
      ]
    end

    def default_invariants
      [
        'DhanHQ only - no other broker integration exists or should be added',
        'exit_engine.rb is the single source of truth for exit placement',
        'TickQuery returns nil (not zero) on cache miss',
        'Position sizing must go through capital/',
        'Solid Queue only, never Sidekiq',
        'Redis tick cache is write-through; must degrade gracefully if Redis is down',
        'Never write to DB from inside a WebSocket tick handler',
        'Live::Gateway is deprecated - use Orders::GatewayLive directly',
        'Gateway (paper/live) is chosen once at boot - changing LIVE_TRADING requires restart',
        'Strategies::Loader uses load (eval) for strategy code - security scanning is mandatory',
      ]
    end

    def default_new_subsystems
      [
        { name: 'Strategies Plugin System', path: 'app/services/strategies/', fileCount: 11, description: 'Hot-loadable, versioned, DB-backed strategy plugins with SHA-256 checksum verification, security scanning, deploy pipeline, and lifecycle management' },
        { name: 'AutoExp', path: 'app/services/auto_exp/', fileCount: 6, description: 'LLM-driven automated config experiments: plan - backtest - evaluate - apply. Full experiment lifecycle.' },
        { name: 'EventStore', path: 'app/services/event_store/', fileCount: 3, description: 'Publisher, DecisionTrace, ReplayEngine for full decision audit trail' },
        { name: 'Policies', path: 'app/services/policies/', fileCount: 4, description: 'Explicit BasePolicy, EntryPolicy, ExitPolicy, RiskPolicy classes' },
        { name: 'Market Context', path: 'app/services/market_context/', fileCount: 5, description: 'ParticipationAnalyzer, RegimeComposer, RegimeSnapshot, StructureAnalyzer, VolatilityAnalyzer' },
        { name: 'Market State', path: 'app/services/market_state/', fileCount: 4, description: 'VolatilityDetector, MarketStateEngine, FeatureStore, TrendDetector' },
        { name: 'Core EventBus', path: 'app/services/core/event_bus.rb', fileCount: 1, description: 'Singleton pub/sub for candle_closed and strategy_status_change events' },
        { name: 'Backtest Engine', path: 'app/services/backtest/', fileCount: 14, description: 'Full backtest subsystem: engine, market replayer, option trade simulator, strategy adapter, SMC replay, metrics, report' },
        { name: 'Data Quality', path: 'app/services/data_quality/', fileCount: 2, description: 'TickStalenessSampler + DailyCheck for monitoring feed/data health' },
      ]
    end

    def default_concerns
      [
        { severity: 'critical', title: 'Triple Signal Path Coexistence', description: 'Signal::Scheduler (30s polling) AND Strategies::Manager (2s EventBus) AND Signal::Engine all registered and running simultaneously. Manager says it "replaces" Scheduler but both start. Risk of duplicate/conflicting signals.' },
        { severity: 'high', title: 'Duplicate recurring job in dev', description: 'dhan_auto_ip_sync appears twice in recurring.yml development section. SolidQueue may silently deduplicate.' },
        { severity: 'high', title: '200+ backtest artifacts in git', description: 'lib/trading_system/algo_trading_system/backtest_results/ contains ~200 generated files (JSON, CSV, HTML) committed to repo.' },
        { severity: 'medium', title: 'Strategy eval security', description: 'Strategies::Loader uses load (eval) for strategy code. Security scanning exists but risk surface is significant.' },
        { severity: 'medium', title: 'Ruby 3.4+ CSV gem', description: 'Gemfile adds csv gem with require: false for Ruby 3.4+ compatibility. May fail if code does require csv directly.' },
        { severity: 'low', title: 'Recent token re-encryption', description: 'Migration reencrypt_existing_dhan_access_tokens implies a security fix was applied to stored tokens.' },
      ]
    end
  end
end