# frozen_string_literal: true

# Adapter to convert strategy signals to Signal::Engine format
module Signal
  class StrategyAdapter
    class << self
      # Convert strategy signal to direction format
      # @param strategy_signal [Hash, nil] Signal from strategy (e.g., { type: :ce, confidence: 70 })
      # @return [Symbol] :bullish, :bearish, or :avoid
      def strategy_to_direction(strategy_signal)
        return :avoid unless strategy_signal

        case strategy_signal[:type]
        when :ce
          :bullish
        when :pe
          :bearish
        else
          :avoid
        end
      end

      # Analyze using a strategy class
      # @param strategy_class [Class] Strategy class (e.g., SimpleMomentumStrategy)
      # @param series [CandleSeries] Candle series
      # @param index [Integer] Current candle index
      # @param strategy_config [Hash] Optional strategy configuration
      # @return [Hash] Analysis result in Signal::Engine format
      def analyze_with_strategy(strategy_class:, series:, index:, strategy_config: {})
        strategy = strategy_class.new(series: series, **strategy_config)
        signal = strategy.generate_signal(index)

        direction = strategy_to_direction(signal)
        confidence = signal ? signal[:confidence] : 0

        if signal.nil?
          Rails.logger.debug("[Signal::StrategyAdapter] No signal generated by #{strategy_class.name} at index #{index} (candles: #{series.candles.size})")
        else
          Rails.logger.debug("[Signal::StrategyAdapter] Signal generated: #{signal[:type]} with confidence #{confidence}%")
        end

        {
          status: :ok,
          series: series,
          direction: direction,
          confidence: confidence,
          strategy_signal: signal,
          last_candle_timestamp: series.candles.last&.timestamp
        }
      rescue StandardError => e
        Rails.logger.error("[Signal::StrategyAdapter] Strategy analysis failed: #{e.class} - #{e.message}")
        { status: :error, message: e.message }
      end
    end
  end
end
