// AUTO-GENERATED by scripts/scan_architecture.rb at 2026-08-25 10:09
// DO NOT EDIT MANUALLY — regenerate with: ruby scripts/scan_architecture.rb > architecture-dashboard/src/lib/architecture-data.ts

export interface Delta { metric: string; review: string; actual: string; direction: 'up' | 'down' | 'same'; }

export const deltas: Delta[] = [
  {
      metric: 'Registered Services',
      review: '19',
      actual: '19',
      direction: 'same'
    },
  {
      metric: 'Entry Guards',
      review: '33',
      actual: '44',
      direction: 'up'
    },
  {
      metric: 'AI Subsystems',
      review: '4',
      actual: '6',
      direction: 'up'
    },
  {
      metric: 'API Endpoints',
      review: '68',
      actual: '71',
      direction: 'up'
    },
  {
      metric: 'Recurring Jobs',
      review: '31',
      actual: '16',
      direction: 'down'
    },
  {
      metric: 'DB Tables',
      review: '58',
      actual: '78',
      direction: 'up'
    },
  {
      metric: 'Signal Paths',
      review: '2',
      actual: '3 (all active)',
      direction: 'up'
    },
  {
      metric: 'Risk Rules',
      review: '~8',
      actual: '25',
      direction: 'up'
    }
];

export interface Service { key: string; name: string; cls: string; cadence: string; category: string; status: string; }
export const services: Service[] = [
  {
      key: 'market_feed',
      name: 'Market Feed',
      cls: 'feed',
      cadence: 'on_tick',
      category: 'market',
      status: 'active'
    },
  {
      key: 'tick_smc_ai',
      name: 'Tick Smc Ai',
      cls: 'Smc::TickAi::AnalysisService',
      cadence: 'on_tick',
      category: 'market',
      status: 'active'
    },
  {
      key: 'signal_scheduler',
      name: 'Signal Scheduler',
      cls: 'Signal::Scheduler',
      cadence: 'on_tick',
      category: 'signal',
      status: 'active'
    },
  {
      key: 'risk_manager',
      name: 'Risk Manager',
      cls: 'Live::RiskManagerService',
      cadence: 'on_tick',
      category: 'risk',
      status: 'active'
    },
  {
      key: 'position_heartbeat',
      name: 'Position Heartbeat',
      cls: 'TradingSystem::PositionHeartbeat',
      cadence: 'on_tick',
      category: 'position',
      status: 'active'
    },
  {
      key: 'order_router',
      name: 'Order Router',
      cls: 'router',
      cadence: 'on_tick',
      category: 'order',
      status: 'active'
    },
  {
      key: 'paper_pnl_refresher',
      name: 'Paper Pnl Refresher',
      cls: 'Live::PaperPnlRefresher',
      cadence: 'on_tick',
      category: 'position',
      status: 'active'
    },
  {
      key: 'exit_manager',
      name: 'Exit Manager',
      cls: 'exit_engine',
      cadence: 'on_tick',
      category: 'exit',
      status: 'active'
    },
  {
      key: 'active_cache',
      name: 'Active Cache',
      cls: 'Positions::ActiveCacheService',
      cadence: 'on_tick',
      category: 'cache',
      status: 'active'
    },
  {
      key: 'reconciliation',
      name: 'Reconciliation',
      cls: 'Live::ReconciliationService',
      cadence: 'on_tick',
      category: 'stats',
      status: 'active'
    },
  {
      key: 'stats_notifier',
      name: 'Stats Notifier',
      cls: 'Live::StatsNotifierService',
      cadence: 'on_tick',
      category: 'stats',
      status: 'active'
    },
  {
      key: 'smc_scanner',
      name: 'Smc Scanner',
      cls: 'Smc::Scanner',
      cadence: 'on_tick',
      category: 'smc',
      status: 'active'
    },
  {
      key: 'strategy_manager',
      name: 'Strategy Manager',
      cls: 'Strategies::Manager',
      cadence: 'on_tick',
      category: 'strategy',
      status: 'active'
    },
  {
      key: 'pnl_updater',
      name: 'Pnl Updater',
      cls: 'Live::PnlUpdaterService',
      cadence: 'on_tick',
      category: 'position',
      status: 'active'
    },
  {
      key: 'candle_poller',
      name: 'Candle Poller',
      cls: 'Live::CandlePollerService',
      cadence: 'on_tick',
      category: 'candle',
      status: 'active'
    },
  {
      key: 'adaptive_supertrend_knn',
      name: 'Adaptive Supertrend Knn',
      cls: 'strategies/adaptive_supertrend_knn',
      cadence: 'plugin',
      category: 'strategy',
      status: 'active'
    },
  {
      key: 'supertrend-adx',
      name: 'Supertrend-Adx',
      cls: 'strategies/supertrend-adx',
      cadence: 'plugin',
      category: 'strategy',
      status: 'active'
    },
  {
      key: 'supertrend_v1',
      name: 'Supertrend V1',
      cls: 'strategies/supertrend_v1',
      cadence: 'plugin',
      category: 'strategy',
      status: 'active'
    },
  {
      key: 'vwap-reversal',
      name: 'Vwap-Reversal',
      cls: 'strategies/vwap-reversal',
      cadence: 'plugin',
      category: 'strategy',
      status: 'active'
    }
];

export interface Guard { name: string; category: string; description: string; isNew: boolean; }
export const entryGuards: Guard[] = [
  {
      name: 'banknifty last week guard',
      category: 'General',
      description: 'banknifty last week guard',
      isNew: false
    },
  {
      name: 'base guard',
      category: 'General',
      description: 'Base for pipeline guards. Each guard implements .call(context) → :pass or { bloc...',
      isNew: false
    },
  {
      name: 'bid ask spread guard',
      category: 'General',
      description: 'Quantity / order-depth-aware checks (enabled only when config threshold > 0 and ...',
      isNew: false
    },
  {
      name: 'bos contract guard',
      category: 'General',
      description: 'bos contract guard',
      isNew: false
    },
  {
      name: 'bos structure guard',
      category: 'General',
      description: 'Constants from EntryGuard (temporary duplicate or move to a common location)',
      isNew: false
    },
  {
      name: 'breakout ready guard',
      category: 'General',
      description: 'Bullish/long-CE needs the CE call-wall resistance; bearish/long-PE needs the',
      isNew: false
    },
  {
      name: 'chain confirmation guard',
      category: 'General',
      description: 'Confirms the already-picked strike has live OI/IV/delta support before',
      isNew: false
    },
  {
      name: 'chop score guard',
      category: 'General',
      description: 'Blocks noisy 1m Supertrend entries when objective chop conditions dominate.',
      isNew: false
    },
  {
      name: 'circuit breaker guard',
      category: 'Risk',
      description: 'circuit breaker guard',
      isNew: false
    },
  {
      name: 'compression setup guard',
      category: 'General',
      description: 'Core entry gate — fail CLOSED: an error must not let a non-setup entry through.',
      isNew: false
    },
  {
      name: 'cooldown guard',
      category: 'General',
      description: 'cooldown guard',
      isNew: false
    },
  {
      name: 'daily limits guard',
      category: 'General',
      description: 'Only block on loss/profit limits, NOT trade frequency limits',
      isNew: false
    },
  {
      name: 'direction conflict guard',
      category: 'Trend',
      description: 'Runs after ChopScoreGuard, so any signal reaching here has already',
      isNew: false
    },
  {
      name: 'drawdown guard',
      category: 'Risk',
      description: 'drawdown guard',
      isNew: false
    },
  {
      name: 'dte entry window guard',
      category: 'Expiry',
      description: 'Blocks new entries after DTE-specific max_entry_time (e.g. 0-DTE after 12:30).',
      isNew: false
    },
  {
      name: 'dynamic regime direction guard',
      category: 'Trend',
      description: 'Dynamically verifies 15-minute price structure regime (Market::MarketRegimeResol...',
      isNew: false
    },
  {
      name: 'earliest entry guard',
      category: 'General',
      description: 'Blocks entries before per-index or global earliest_entry_time (IST).',
      isNew: false
    },
  {
      name: 'edge failure guard',
      category: 'General',
      description: 'edge failure guard',
      isNew: false
    },
  {
      name: 'entry policy guard',
      category: 'General',
      description: 'entry policy guard',
      isNew: false
    },
  {
      name: 'expiry week power trend guard',
      category: 'Trend',
      description: 'Detects the "expiry-week afternoon power trend" pattern and enriches entry conte...',
      isNew: false
    },
  {
      name: 'exposure guard',
      category: 'General',
      description: 'exposure guard',
      isNew: false
    },
  {
      name: 'feed health guard',
      category: 'General',
      description: 'Blocks entries when any required market-data feed is stale or has never synced.',
      isNew: false
    },
  {
      name: 'global max concurrent guard',
      category: 'General',
      description: 'Portfolio-level max concurrent positions guard.',
      isNew: false
    },
  {
      name: 'index trade limit guard',
      category: 'General',
      description: 'Enforces per-index trade_limits.max_trades_per_day from index config.',
      isNew: false
    },
  {
      name: 'instrument lookup guard',
      category: 'General',
      description: 'instrument lookup guard',
      isNew: false
    },
  {
      name: 'iv vol gate guard',
      category: 'General',
      description: 'Entry guard that gates entries based on the options implied volatility (IV) ran...s implied volatility (IV) ran...',
      isNew: false
    },
  {
      name: 'loss streak guard',
      category: 'Risk',
      description: 'loss streak guard',
      isNew: false
    },
  {
      name: 'ltp resolution guard',
      category: 'General',
      description: 'Log WebSocket status but never block',
      isNew: false
    },
  {
      name: 'margin limit guard',
      category: 'General',
      description: 'Selling requires SPAN + exposure margin (5-20x the premium), not just the',
      isNew: false
    },
  {
      name: 'max concurrent guard',
      category: 'General',
      description: 'max concurrent guard',
      isNew: false
    },
  {
      name: 'midday quality guard',
      category: 'Signal',
      description: 'Edge case: some signals store `regime_confidence: 0` to mean "not computed".',
      isNew: false
    },
  {
      name: 'momentum gate guard',
      category: 'Trend',
      description: 'momentum gate guard',
      isNew: false
    },
  {
      name: 'option volume velocity guard',
      category: 'General',
      description: 'Entry guard that verifies that the option contracts volume velocitys volume velocity',
      isNew: false
    },
  {
      name: 'premium band guard',
      category: 'General',
      description: 'Blocks entries when option premium is outside the configured band for the index.',
      isNew: false
    },
  {
      name: 'regime guard',
      category: 'Market',
      description: 'regime guard',
      isNew: false
    },
  {
      name: 'risk policy guard',
      category: 'Risk',
      description: 'risk policy guard',
      isNew: false
    },
  {
      name: 'segment expectancy guard',
      category: 'General',
      description: 'Blocks new entries into (index, session-regime) segments that the bots owns own',
      isNew: false
    },
  {
      name: 'selling iv rank guard',
      category: 'General',
      description: 'Selling profits from IV richness (the opposite of IvVolGateGuards buyings buying',
      isNew: false
    },
  {
      name: 'sizing guard',
      category: 'General',
      description: 'sizing guard',
      isNew: false
    },
  {
      name: 'smc navigator guard',
      category: 'General',
      description: 'LTF SMC overlay (zone + liquidity + swing trend). Runs after LTP resolution.',
      isNew: false
    },
  {
      name: 'strike cooldown guard',
      category: 'General',
      description: 'Blocks re-entry of the same option contract (security_id) within a',
      isNew: false
    },
  {
      name: 'time regime guard',
      category: 'Timing',
      description: 'time regime guard',
      isNew: false
    },
  {
      name: 'vix gate guard',
      category: 'Volatility',
      description: 'vix gate guard',
      isNew: false
    },
  {
      name: 'weekly expiry guard',
      category: 'Expiry',
      description: 'weekly expiry guard',
      isNew: false
    }
];

export const riskRules: string[] = [
  'base_rule',
  'dte_zero_theta_flat_exit_rule',
  'early_trend_failure_rule',
  'emergency_peak_loss_rule',
  'fast_profit_lock_rule',
  'greeks_decay_exit_rule',
  'green_trade_cap_rule',
  'iv_collapse_rule',
  'max_premium_loss_rule',
  'percentage_pnl_rule',
  'portfolio_floor_rule',
  'premium_momentum_failure_rule',
  'premium_target_rule',
  'secure_profit_rule',
  'session_end_rule',
  'smc_navigator_rule',
  'stop_loss_rule',
  'structural_kill_switch_rule',
  'structure_invalidation_rule',
  'take_profit_rule',
  'time_based_exit_rule',
  'time_stop_rule',
  'trailing_stop_rule',
  'vix_force_exit_rule',
  'zero_hwm_false_entry_rule'
];

export const optionsBuyingStrategies: string[] = [
  'base_strategy',
  'iv_percentile_confluence',
  'orb_breakout',
  'supertrend_adx',
  'triple_tf_alignment',
  'vcp_breakout',
  'vix_expansion'
];

export interface DbTable { table: string; category: string; isNew: boolean; }
export const dbTables: DbTable[] = [
  {
      table: 'agent_decision_logs',
      category: 'System',
      isNew: false
    },
  {
      table: 'algo_config_change_logs',
      category: 'System',
      isNew: false
    },
  {
      table: 'alpha_signals',
      category: 'Trading',
      isNew: false
    },
  {
      table: 'audit_logs',
      category: 'System',
      isNew: false
    },
  {
      table: 'backtest_runs',
      category: 'Research',
      isNew: false
    },
  {
      table: 'best_indicator_params',
      category: 'Other',
      isNew: false
    },
  {
      table: 'calibration_runs',
      category: 'Strategy',
      isNew: false
    },
  {
      table: 'candles',
      category: 'Market',
      isNew: false
    },
  {
      table: 'data_quality_daily_metrics',
      category: 'Other',
      isNew: false
    },
  {
      table: 'derivatives',
      category: 'Market',
      isNew: false
    },
  {
      table: 'dhan_access_tokens',
      category: 'Auth',
      isNew: false
    },
  {
      table: 'instruments',
      category: 'Market',
      isNew: false
    },
  {
      table: 'iv_snapshots',
      category: 'Other',
      isNew: false
    },
  {
      table: 'ledger_accounts',
      category: 'Ledger',
      isNew: false
    },
  {
      table: 'ledger_journal_entries',
      category: 'Ledger',
      isNew: false
    },
  {
      table: 'ledger_postings',
      category: 'Ledger',
      isNew: false
    },
  {
      table: 'leg_groups',
      category: 'Other',
      isNew: false
    },
  {
      table: 'market_holidays',
      category: 'Market',
      isNew: false
    },
  {
      table: 'options_buying_signal_events',
      category: 'Trading',
      isNew: false
    },
  {
      table: 'order_intents',
      category: 'Trading',
      isNew: false
    },
  {
      table: 'paper_daily_wallets',
      category: 'Ledger',
      isNew: false
    },
  {
      table: 'paper_fills_logs',
      category: 'System',
      isNew: false
    },
  {
      table: 'paper_orders',
      category: 'Trading',
      isNew: false
    },
  {
      table: 'paper_positions',
      category: 'Trading',
      isNew: false
    },
  {
      table: 'paper_trades',
      category: 'Trading',
      isNew: false
    },
  {
      table: 'paper_wallets',
      category: 'Ledger',
      isNew: false
    },
  {
      table: 'platform_variables',
      category: 'Other',
      isNew: false
    },
  {
      table: 'position_meta_snapshots',
      category: 'Trading',
      isNew: false
    },
  {
      table: 'position_trackers',
      category: 'Trading',
      isNew: false
    },
  {
      table: 'public_ip_logs',
      category: 'System',
      isNew: false
    },
  {
      table: 'reconciliation_discrepancies',
      category: 'Other',
      isNew: false
    },
  {
      table: 'reconciliation_runs',
      category: 'Other',
      isNew: false
    },
  {
      table: 'research_data_quality_audits',
      category: 'Research',
      isNew: false
    },
  {
      table: 'research_dataset_snapshots',
      category: 'Research',
      isNew: false
    },
  {
      table: 'research_edge_registry',
      category: 'Research',
      isNew: false
    },
  {
      table: 'research_event_exits',
      category: 'Research',
      isNew: false
    },
  {
      table: 'research_event_strikes',
      category: 'Research',
      isNew: false
    },
  {
      table: 'research_events',
      category: 'Research',
      isNew: false
    },
  {
      table: 'research_experiment_registry',
      category: 'Research',
      isNew: false
    },
  {
      table: 'research_feature_importances',
      category: 'Research',
      isNew: false
    },
  {
      table: 'research_feature_registry',
      category: 'Research',
      isNew: false
    },
  {
      table: 'research_hypotheses',
      category: 'Research',
      isNew: false
    },
  {
      table: 'research_option_bars',
      category: 'Research',
      isNew: false
    },
  {
      table: 'research_option_candidates',
      category: 'Research',
      isNew: false
    },
  {
      table: 'research_premium_lifecycles',
      category: 'Research',
      isNew: false
    },
  {
      table: 'research_raw_fetches',
      category: 'Research',
      isNew: false
    },
  {
      table: 'research_signals',
      category: 'Trading',
      isNew: false
    },
  {
      table: 'risk_events',
      category: 'Other',
      isNew: false
    },
  {
      table: 'ruby_llm_agents_execution_details',
      category: 'Other',
      isNew: false
    },
  {
      table: 'ruby_llm_agents_executions',
      category: 'Other',
      isNew: false
    },
  {
      table: 'ruby_llm_agents_overrides',
      category: 'Other',
      isNew: false
    },
  {
      table: 'settings',
      category: 'System',
      isNew: false
    },
  {
      table: 'smc_events',
      category: 'Other',
      isNew: false
    },
  {
      table: 'solid_queue_blocked_executions',
      category: 'Other',
      isNew: false
    },
  {
      table: 'solid_queue_claimed_executions',
      category: 'Other',
      isNew: false
    },
  {
      table: 'solid_queue_failed_executions',
      category: 'Other',
      isNew: false
    },
  {
      table: 'solid_queue_jobs',
      category: 'Other',
      isNew: false
    },
  {
      table: 'solid_queue_pauses',
      category: 'Other',
      isNew: false
    },
  {
      table: 'solid_queue_processes',
      category: 'Other',
      isNew: false
    },
  {
      table: 'solid_queue_ready_executions',
      category: 'Other',
      isNew: false
    },
  {
      table: 'solid_queue_recurring_executions',
      category: 'Other',
      isNew: false
    },
  {
      table: 'solid_queue_recurring_tasks',
      category: 'Other',
      isNew: false
    },
  {
      table: 'solid_queue_scheduled_executions',
      category: 'Other',
      isNew: false
    },
  {
      table: 'solid_queue_semaphores',
      category: 'Other',
      isNew: false
    },
  {
      table: 'strategies',
      category: 'Other',
      isNew: false
    },
  {
      table: 'strategy_runs',
      category: 'Strategy',
      isNew: false
    },
  {
      table: 'strategy_signals',
      category: 'Trading',
      isNew: false
    },
  {
      table: 'strategy_versions',
      category: 'Strategy',
      isNew: false
    },
  {
      table: 'trade_analytics',
      category: 'Trading',
      isNew: false
    },
  {
      table: 'trade_journals',
      category: 'Trading',
      isNew: false
    },
  {
      table: 'trade_memories',
      category: 'Trading',
      isNew: false
    },
  {
      table: 'trade_telemetry',
      category: 'Trading',
      isNew: false
    },
  {
      table: 'trading_signals',
      category: 'Trading',
      isNew: false
    },
  {
      table: 'trading_strategies',
      category: 'Other',
      isNew: false
    },
  {
      table: 'watchlist_items',
      category: 'Other',
      isNew: false
    },
  {
      table: 'woods_edges',
      category: 'Other',
      isNew: false
    },
  {
      table: 'woods_embeddings',
      category: 'Other',
      isNew: false
    },
  {
      table: 'woods_units',
      category: 'Other',
      isNew: false
    }
];

export interface ApiEndpoint { method: string; path: string; isNew: boolean; }
export const apiEndpoints: ApiEndpoint[] = [
  {
      method: 'GET',
      path: 'up',
      isNew: false
    },
  {
      method: 'GET',
      path: 'smc/decision',
      isNew: false
    },
  {
      method: 'GET',
      path: 'settings',
      isNew: false
    },
  {
      method: 'GET',
      path: 'settings/change_logs',
      isNew: false
    },
  {
      method: 'PATCH',
      path: 'settings/bulk',
      isNew: false
    },
  {
      method: 'GET',
      path: 'settings/fast_entry_mode',
      isNew: false
    },
  {
      method: 'PATCH',
      path: 'settings/fast_entry_mode',
      isNew: false
    },
  {
      method: 'POST',
      path: 'settings/update_ip',
      isNew: false
    },
  {
      method: 'PATCH',
      path: 'settings/deep_merge',
      isNew: false
    },
  {
      method: 'GET',
      path: 'dashboard',
      isNew: false
    },
  {
      method: 'GET',
      path: 'orders',
      isNew: false
    },
  {
      method: 'GET',
      path: 'equity_curve',
      isNew: false
    },
  {
      method: 'GET',
      path: 'signals',
      isNew: false
    },
  {
      method: 'GET',
      path: 'analysis/:index_key',
      isNew: false
    },
  {
      method: 'GET',
      path: 'analysis/:index_key/historical',
      isNew: false
    },
  {
      method: 'POST',
      path: 'analysis/:index_key/ai_snapshot',
      isNew: false
    },
  {
      method: 'GET',
      path: 'candles/:index_key',
      isNew: false
    },
  {
      method: 'GET',
      path: 'option_chain/:index_key',
      isNew: false
    },
  {
      method: 'GET',
      path: 'depth',
      isNew: false
    },
  {
      method: 'GET',
      path: 'market/vix',
      isNew: false
    },
  {
      method: 'POST',
      path: 'drawdown_guard/reset',
      isNew: false
    },
  {
      method: 'GET',
      path: 'public_ip/audit',
      isNew: false
    },
  {
      method: 'GET',
      path: 'dhan_access_token',
      isNew: false
    },
  {
      method: 'GET',
      path: 'alpha/status',
      isNew: false
    },
  {
      method: 'GET',
      path: 'alpha/history',
      isNew: false
    },
  {
      method: 'GET',
      path: 'alpha/performance',
      isNew: false
    },
  {
      method: 'GET',
      path: 'ledger/balance',
      isNew: false
    },
  {
      method: 'GET',
      path: 'ledger/journal',
      isNew: false
    },
  {
      method: 'GET',
      path: 'ledger/position',
      isNew: false
    },
  {
      method: 'GET',
      path: 'funds',
      isNew: false
    },
  {
      method: 'POST',
      path: 'funds/add',
      isNew: false
    },
  {
      method: 'POST',
      path: 'funds/withdraw',
      isNew: false
    },
  {
      method: 'GET',
      path: 'holdings',
      isNew: false
    },
  {
      method: 'GET',
      path: 'logs',
      isNew: false
    },
  {
      method: 'GET',
      path: 'reports',
      isNew: false
    },
  {
      method: 'GET',
      path: 'reports/pnl',
      isNew: false
    },
  {
      method: 'GET',
      path: 'reports/trades',
      isNew: false
    },
  {
      method: 'GET',
      path: 'reports/performance',
      isNew: false
    },
  {
      method: 'GET',
      path: 'reports/pnl_by_strategy',
      isNew: false
    },
  {
      method: 'GET',
      path: 'reports/pnl_by_instrument',
      isNew: false
    },
  {
      method: 'GET',
      path: 'reports/export',
      isNew: false
    },
  {
      method: 'GET',
      path: 'scheduler/tasks',
      isNew: false
    },
  {
      method: 'POST',
      path: 'scheduler/tasks/:id/execute',
      isNew: false
    },
  {
      method: 'POST',
      path: 'backtests',
      isNew: false
    },
  {
      method: 'POST',
      path: 'replays',
      isNew: false
    },
  {
      method: 'GET',
      path: 'variables',
      isNew: false
    },
  {
      method: 'PUT',
      path: 'variables',
      isNew: false
    },
  {
      method: 'GET',
      path: 'strategies/health/pool',
      isNew: false
    },
  {
      method: 'GET',
      path: 'strategies/health/session',
      isNew: false
    },
  {
      method: 'GET',
      path: 'strategies/health/backtest',
      isNew: false
    },
  {
      method: 'GET',
      path: 'redis_ui',
      isNew: false
    },
  {
      method: 'GET',
      path: 'redis_ui/info',
      isNew: false
    },
  {
      method: 'GET',
      path: 'redis_ui/:id',
      isNew: false
    },
  {
      method: 'DELETE',
      path: 'redis_ui/:id',
      isNew: false
    },
  {
      method: 'GET',
      path: '/.well-known/*path',
      isNew: false
    },
  {
      method: 'REST',
      path: '/positions',
      isNew: false
    },
  {
      method: 'REST',
      path: '/positions/:id',
      isNew: false
    },
  {
      method: 'REST',
      path: '/alerts',
      isNew: false
    },
  {
      method: 'REST',
      path: '/alerts/:id',
      isNew: false
    },
  {
      method: 'REST',
      path: '/backtest_runs',
      isNew: false
    },
  {
      method: 'REST',
      path: '/backtest_runs/:id',
      isNew: false
    },
  {
      method: 'REST',
      path: '/calibration_runs',
      isNew: false
    },
  {
      method: 'REST',
      path: '/calibration_runs/:id',
      isNew: false
    },
  {
      method: 'REST',
      path: '/trading_strategies',
      isNew: false
    },
  {
      method: 'REST',
      path: '/trading_strategies/:id',
      isNew: false
    },
  {
      method: 'REST',
      path: '/strategies',
      isNew: false
    },
  {
      method: 'REST',
      path: '/strategies/:id',
      isNew: false
    },
  {
      method: 'REST',
      path: '/lifecycles',
      isNew: false
    },
  {
      method: 'REST',
      path: '/lifecycles/:id',
      isNew: false
    },
  {
      method: 'REST',
      path: '/signals',
      isNew: false
    },
  {
      method: 'REST',
      path: '/signals/:id',
      isNew: false
    }
];

export interface RecurringJob { name: string; schedule: string; phase: string; }
export const recurringJobs: RecurringJob[] = [
  {
      name: 'InstrumentsImportJob',
      schedule: '8:45am weekdays',
      phase: 'pre-market'
    },
  {
      name: 'PortfolioResetJob',
      schedule: '9:14am weekdays',
      phase: 'pre-market'
    },
  {
      name: 'ClearCarriedOvernightPositionsJob',
      schedule: '9:15am weekdays',
      phase: 'pre-market'
    },
  {
      name: 'Clear Solid Queue Finished Jobs',
      schedule: 'every hour',
      phase: 'intraday'
    },
  {
      name: 'SmcScannerJob',
      schedule: 'every 15 min (9:15am-3:30pm)',
      phase: 'intraday'
    },
  {
      name: 'AgentsCycleJob',
      schedule: 'every 15 min (9:15am-3:30pm)',
      phase: 'intraday'
    },
  {
      name: 'AiTechnicalAnalysisJob',
      schedule: '4:00pm weekdays',
      phase: 'post-close'
    },
  {
      name: 'AiTechnicalAnalysisJob',
      schedule: '4:00pm weekdays',
      phase: 'post-close'
    },
  {
      name: 'WeeklyCalibrationJob',
      schedule: 'Sunday 6:00 am IST',
      phase: 'weekly'
    },
  {
      name: 'AutoIpUpdaterJob',
      schedule: 'every 30 min',
      phase: 'intraday'
    },
  {
      name: 'PublicIpLogJob',
      schedule: 'every 15 min',
      phase: 'intraday'
    },
  {
      name: 'CancelStuckOrdersJob',
      schedule: 'every 1 minute (9:15am-3:30pm)',
      phase: 'intraday'
    },
  {
      name: 'DailyCloseJob',
      schedule: '3:35pm weekdays',
      phase: 'post-close'
    },
  {
      name: 'DailyCloseJob',
      schedule: '3:36pm weekdays',
      phase: 'post-close'
    },
  {
      name: 'TickStalenessSamplerJob',
      schedule: 'every 1 minute (9:15am-3:30pm)',
      phase: 'intraday'
    },
  {
      name: 'DailyCheckJob',
      schedule: '3:40pm weekdays',
      phase: 'post-close'
    }
];

export interface AiSubsystem { name: string; path: string; components: string[]; description: string; status: string; }
export const aiSubsystems: AiSubsystem[] = [
  {
      name: 'Trading Bot',
      path: 'app/services/ai/trading_bot',
      components: ['analyst', 'config', 'engine', 'notifier', 'scanner', 'self_learning', 'trader'],
      description: 'Semi-autonomous scan-analyze-trade loop (Ollama-backed polling)',
      status: 'active'
    },
  {
      name: 'Trading Agent',
      path: 'app/services/ai/trading_agent',
      components: ['agent_loop', 'prompt_builder', 'repl', 'risk_validator', 'terminal_markdown', 'tool_registry', 'trace_logger'],
      description: 'LLM tool-calling agent with REPL and audit trace',
      status: 'active'
    },
  {
      name: 'AI Calibration',
      path: 'app/services/ai/calibration',
      components: ['backtest_validator', 'config_applier', 'dataset_builder', 'prompt_builder', 'result_parser', 'runner'],
      description: 'Weekly automated indicator calibration via LLM',
      status: 'active'
    },
  {
      name: 'Autonomous',
      path: 'app/services/ai/autonomous',
      components: ['auditor', 'orchestrator', 'task_runner'],
      description: 'LLM experiment runner with Observe-Think-Act loop',
      status: 'experimental'
    },
  {
      name: 'AutoExp',
      path: 'app/services/auto_exp',
      components: ['backtest_executor', 'config_applier', 'evaluator', 'experiment_runner', 'llm_planner', 'results_store'],
      description: 'LLM-driven automated config experiments: plan - backtest - evaluate - apply',
      status: 'new'
    },
  {
      name: 'Trading Orchestrator',
      path: 'app/services/agents',
      components: ['trading_orchestrator'],
      description: 'LLM-chained MarketAnalyst - Strategy - Risk - OptionSelector pipeline',
      status: 'overlapping'
    }
];

// ─── Static Data (manually curated from repo audit, update as needed) ─────────

export interface TechLayer { layer: string; technology: string; }
export const techStack: TechLayer[] = [
  {
      layer: 'Language/Framework',
      technology: 'Ruby 3.3.4, Rails 8.1.3 (API-only)'
    },
  {
      layer: 'Job Backend',
      technology: 'Solid Queue'
    },
  {
      layer: 'WebSocket',
      technology: 'Solid Cable'
    },
  {
      layer: 'Cache',
      technology: 'Solid Cache'
    },
  {
      layer: 'Database',
      technology: 'PostgreSQL 15'
    },
  {
      layer: 'Queue Store',
      technology: 'Redis 7'
    },
  {
      layer: 'Broker API',
      technology: 'DhanHQ v2'
    },
  {
      layer: 'LLM Runtime',
      technology: 'Ollama (local)'
    },
  {
      layer: 'AI Framework',
      technology: 'ruby_llm-agents'
    },
  {
      layer: 'Frontend',
      technology: 'Vite + SolidJS/Vue (main), Next.js (arch)'
    },
  {
      layer: 'Deployment',
      technology: 'Docker Compose (6 processes)'
    }
];

export interface ProcessModel { process: string; command: string; role: string; }
export const processModel: ProcessModel[] = [
  {
      process: 'web',
      command: 'bin/rails server (Puma)',
      role: 'Rails API — REST endpoints, WebSocket cable, static assets'
    },
  {
      process: 'jobs',
      command: 'bin/jobs (Solid Queue)',
      role: 'Background jobs — scheduled tasks, research pipeline'
    },
  {
      process: 'dashboard',
      command: 'Vite / nginx :3000',
      role: 'Main trading dashboard — positions, signals, option chain'
    },
  {
      process: 'arch-dashboard',
      command: 'Next.js standalone :3003',
      role: 'Architecture dashboard — live codebase visualization'
    }
];

export const indexParams = [
  {
      index: 'NIFTY',
      capital: '30%',
      premium: '30-160',
      risk: '1%',
      maxTrades: 3
    },
  {
      index: 'BANKNIFTY',
      capital: '30%',
      premium: '60-650',
      risk: '2%',
      maxTrades: 3
    },
  {
      index: 'SENSEX',
      capital: '30%',
      premium: '40-320',
      risk: '2%',
      maxTrades: 3
    }
];

export const smcDetectors: string[] = [
  'fvg',
  'order_blocks',
  'liquidity',
  'structure',
  'swing_structure',
  'internal_structure',
  'premium_discount'
];

export const lockedPaths: string[] = [
  'DhanHQ gateways/adapters',
  'WebSocket/market-data/caching (market_feed_hub, order_update_hub, redis_tick_cache)',
  'Position lifecycle (active_cache, serializer, positions/states/*)',
  'Order execution plumbing (orders/commands/*, executor, entry_manager, FSM, bracket placer)',
  'Exit engine (exit_engine, trailing_engine, mfe_exit_engine, gamma_trailing_engine)',
  'Risk-manager plumbing',
  'Process wiring (lib/trading_system/, jobs, controllers/routes)',
  'Instrument/chain plumbing (instrument.rb, chain_analyzer.rb, strike_selector.rb)'
];

export const alphaPaths: string[] = [
  'signal/*',
  'indicators/*',
  'market_state/*',
  'market_context/*',
  'smc/*',
  'trading/trend_scorer.rb',
  'trading/permission_resolver.rb',
  'entries/entry_guard.rb, entry_filter_engine, entry_guard_pipeline',
  'All entries/guards/*',
  'orders/analyzer.rb, adjuster.rb, adaptive_trailing.rb, gamma_detector.rb',
  'All risk/*, all policies/*',
  'capital/allocator.rb',
  'options/flow_analyzer.rb, strike_qualification/*',
  'options/historical_calibration_engine.rb',
  'auto_exp/* (new experiment framework)',
  'backtest/* (new backtest subsystem)',
  'event_store/* (new decision audit trail)'
];

export const tokenFallback: string[] = [
  'Authority server HTTP GET ($TRADER_API_BASE_URL/auth/dhan/token, 60s cache)',
  'TOTP auto-refresh (DHAN_PIN + DHAN_TOTP_SECRET via rotp gem)',
  'Static ENV["DHAN_ACCESS_TOKEN"] fallback'
];

export const bootSequence: string[] = [
  'Rails initializers wire DhanHQ config, gateway (paper/live), token bootstrap',
  'Live::PositionSyncService.instance.force_sync! - reconcile DB vs broker',
  'Market::VixGate.evaluate! at boot (VIX entry gating)',
  'supervisor.start_all - launches all daemon services'
];

export const docDebt: string[] = [
  'README.md describes 11-service supervisor; actual registry has 16 entries',
  'Signal::Scheduler IS still registered - coexists with Strategies::Manager',
  'Entry guard count documented as 20; actual directory has #{guards.size} guard files',
  'docs/ has ~200+ files, many under docs/archive/ (superseded)',
  '~200 backtest artifact files committed to lib/ (should be in .gitignore)'
];

export const criticalInvariants: string[] = [
  'DhanHQ only - no other broker integration exists or should be added',
  'exit_engine.rb is the single source of truth for exit placement',
  'TickQuery returns nil (not zero) on cache miss',
  'Position sizing must go through capital/',
  'Solid Queue only, never Sidekiq',
  'Redis tick cache is write-through; must degrade gracefully if Redis is down',
  'Never write to DB from inside a WebSocket tick handler',
  'Live::Gateway is deprecated - use Orders::GatewayLive directly',
  'Gateway (paper/live) is chosen once at boot - changing LIVE_TRADING requires restart',
  'Strategies::Loader uses load (eval) for strategy code - security scanning is mandatory'
];

export interface EnvVar { variable: string; required: string; purpose: string; }
export const envVars: EnvVar[] = [
  {
      variable: 'RAILS_LOG_LEVEL',
      required: 'Recommended',
      purpose: ''
    },
  {
      variable: 'RAILS_MAX_THREADS',
      required: 'Recommended',
      purpose: ''
    },
  {
      variable: 'PORT',
      required: 'Recommended',
      purpose: ''
    },
  {
      variable: 'SOLID_QUEUE_IN_PUMA',
      required: 'Recommended',
      purpose: ''
    },
  {
      variable: 'JOB_CONCURRENCY',
      required: 'Recommended',
      purpose: ''
    },
  {
      variable: 'REDIS_URL',
      required: 'Recommended',
      purpose: ''
    },
  {
      variable: 'ALGO_SCALPER_API_DATABASE_PASSWORD',
      required: 'Recommended',
      purpose: ''
    },
  {
      variable: 'DHANHQ_ENABLED',
      required: 'Recommended',
      purpose: ''
    },
  {
      variable: 'ENABLE_TRADING_SERVICES',
      required: 'Recommended',
      purpose: ''
    },
  {
      variable: 'PLACE_ORDER',
      required: 'Recommended',
      purpose: ''
    },
  {
      variable: 'BACKTEST_MODE',
      required: 'Recommended',
      purpose: ''
    },
  {
      variable: 'SCRIPT_MODE',
      required: 'Recommended',
      purpose: ''
    },
  {
      variable: 'DHANHQ_WS_MODE',
      required: 'Recommended',
      purpose: ''
    },
  {
      variable: 'DHANHQ_BASE_URL',
      required: 'Recommended',
      purpose: ''
    },
  {
      variable: 'DHANHQ_WS_VERSION',
      required: 'Recommended',
      purpose: ''
    },
  {
      variable: 'DHAN_CLIENT_ID',
      required: 'Recommended',
      purpose: ''
    },
  {
      variable: 'DHAN_PIN',
      required: 'Recommended',
      purpose: ''
    },
  {
      variable: 'DHAN_TOTP_SECRET',
      required: 'Recommended',
      purpose: ''
    },
  {
      variable: 'DHAN_ACCESS_TOKEN',
      required: 'Recommended',
      purpose: ''
    },
  {
      variable: 'DHANHQ_PARTNER_ID',
      required: 'Recommended',
      purpose: ''
    },
  {
      variable: 'DHANHQ_PARTNER_SECRET',
      required: 'Recommended',
      purpose: ''
    },
  {
      variable: 'DHANHQ_WS_ORDER_URL',
      required: 'Recommended',
      purpose: ''
    },
  {
      variable: 'DHANHQ_WS_USER_TYPE',
      required: 'Recommended',
      purpose: ''
    },
  {
      variable: 'LIVE_TRADING',
      required: 'Recommended',
      purpose: ''
    },
  {
      variable: 'DHANHQ_LOG_LEVEL',
      required: 'Recommended',
      purpose: ''
    },
  {
      variable: 'DHAN_LOG_LEVEL',
      required: 'Recommended',
      purpose: ''
    },
  {
      variable: 'DHANHQ_WS_WATCHLIST',
      required: 'Recommended',
      purpose: ''
    },
  {
      variable: 'RAILS_MASTER_KEY',
      required: 'Recommended',
      purpose: ''
    },
  {
      variable: 'KAMAL_REGISTRY_PASSWORD',
      required: 'Recommended',
      purpose: ''
    },
  {
      variable: 'TELEGRAM_BOT_TOKEN',
      required: 'Recommended',
      purpose: ''
    },
  {
      variable: 'TELEGRAM_CHAT_ID',
      required: 'Recommended',
      purpose: ''
    },
  {
      variable: 'TRADING_BOOT_RECONCILIATION_STRICT',
      required: 'Recommended',
      purpose: ''
    },
  {
      variable: 'ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY',
      required: 'Recommended',
      purpose: ''
    },
  {
      variable: 'ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY',
      required: 'Recommended',
      purpose: ''
    },
  {
      variable: 'ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT',
      required: 'Recommended',
      purpose: ''
    }
];

export interface NewSubsystem { name: string; path: string; fileCount: number; description: string; }
export const newSubsystems: NewSubsystem[] = [
  {
      name: 'Strategies Plugin System',
      path: 'app/services/strategies/',
      fileCount: 11,
      description: 'Hot-loadable, versioned, DB-backed strategy plugins with SHA-256 checksum verification, security scanning, deploy pipeline, and lifecycle management'
    },
  {
      name: 'AutoExp',
      path: 'app/services/auto_exp/',
      fileCount: 6,
      description: 'LLM-driven automated config experiments: plan - backtest - evaluate - apply. Full experiment lifecycle.'
    },
  {
      name: 'EventStore',
      path: 'app/services/event_store/',
      fileCount: 3,
      description: 'Publisher, DecisionTrace, ReplayEngine for full decision audit trail'
    },
  {
      name: 'Policies',
      path: 'app/services/policies/',
      fileCount: 4,
      description: 'Explicit BasePolicy, EntryPolicy, ExitPolicy, RiskPolicy classes'
    },
  {
      name: 'Market Context',
      path: 'app/services/market_context/',
      fileCount: 5,
      description: 'ParticipationAnalyzer, RegimeComposer, RegimeSnapshot, StructureAnalyzer, VolatilityAnalyzer'
    },
  {
      name: 'Market State',
      path: 'app/services/market_state/',
      fileCount: 4,
      description: 'VolatilityDetector, MarketStateEngine, FeatureStore, TrendDetector'
    },
  {
      name: 'Core EventBus',
      path: 'app/services/core/event_bus.rb',
      fileCount: 1,
      description: 'Singleton pub/sub for candle_closed and strategy_status_change events'
    },
  {
      name: 'Backtest Engine',
      path: 'app/services/backtest/',
      fileCount: 14,
      description: 'Full backtest subsystem: engine, market replayer, option trade simulator, strategy adapter, SMC replay, metrics, report'
    },
  {
      name: 'Data Quality',
      path: 'app/services/data_quality/',
      fileCount: 2,
      description: 'TickStalenessSampler + DailyCheck for monitoring feed/data health'
    }
];

export interface Concern { severity: string; title: string; description: string; }
export const concerns: Concern[] = [
  {
      severity: 'critical',
      title: 'Triple Signal Path Coexistence',
      description: 'Signal::Scheduler (30s polling) AND Strategies::Manager (2s EventBus) AND Signal::Engine all registered and running simultaneously. Manager says it "replaces" Scheduler but both start. Risk of duplicate/conflicting signals.'
    },
  {
      severity: 'high',
      title: 'Duplicate recurring job in dev',
      description: 'dhan_auto_ip_sync appears twice in recurring.yml development section. SolidQueue may silently deduplicate.'
    },
  {
      severity: 'high',
      title: '200+ backtest artifacts in git',
      description: 'lib/trading_system/algo_trading_system/backtest_results/ contains ~200 generated files (JSON, CSV, HTML) committed to repo.'
    },
  {
      severity: 'medium',
      title: 'Strategy eval security',
      description: 'Strategies::Loader uses load (eval) for strategy code. Security scanning exists but risk surface is significant.'
    },
  {
      severity: 'medium',
      title: 'Ruby 3.4+ CSV gem',
      description: 'Gemfile adds csv gem with require: false for Ruby 3.4+ compatibility. May fail if code does require csv directly.'
    },
  {
      severity: 'low',
      title: 'Recent token re-encryption',
      description: 'Migration reencrypt_existing_dhan_access_tokens implies a security fix was applied to stored tokens.'
    }
];
